import { useState, useEffect } from 'react';
import axios from 'axios';
import { useAuth } from '../../../context/AuthContext';
import { Shield, Search, Clock, Printer } from 'lucide-react';

const IDCardLogs = () => {
    const { user } = useAuth();
    const [logs, setLogs] = useState([]);
    const [loading, setLoading] = useState(true);
    const [searchTerm, setSearchTerm] = useState('');

    useEffect(() => {
        const fetchLogs = async () => {
            try {
                const config = { headers: { Authorization: `Bearer ${user.token}` } };
                const { data } = await axios.get(`${import.meta.env.VITE_API_URL}/api/idcard/logs`, config);
                setLogs(data);
            } catch (error) {
                console.error("Error fetching logs:", error);
            } finally {
                setLoading(false);
            }
        };
        fetchLogs();
    }, [user]);

    const filteredLogs = logs.filter(log =>
        log.detailsSnapshot?.name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
        log.detailsSnapshot?.rollNumber?.includes(searchTerm) ||
        log.generatedBy?.name?.toLowerCase().includes(searchTerm.toLowerCase())
    );

    return (
        <div className="space-y-6 animate-fade-in p-2 md:p-6">
            <h1 className="text-2xl font-bold dark:text-white flex items-center gap-2">
                <Shield className="h-6 w-6 text-indigo-600" />
                ID Card Generation Logs
            </h1>

            <div className="bg-white/60 dark:bg-[#121212]/60 backdrop-blur-xl p-4 rounded-2xl shadow-sm border border-white/20 dark:border-white/10">
                <div className="relative">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                    <input
                        type="text"
                        placeholder="Search logs by student name, roll no, or generator..."
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                        className="w-full pl-10 p-3 rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-black/30 text-gray-900 dark:text-white focus:ring-2 focus:ring-indigo-500/50 outline-none placeholder:text-gray-500"
                    />
                </div>
            </div>

            <div className="bg-white/60 dark:bg-[#121212]/60 backdrop-blur-xl rounded-2xl shadow-sm border border-white/20 dark:border-white/10 overflow-hidden">
                <div className="overflow-x-auto">
                    <table className="w-full text-sm text-left">
                        <thead className="text-xs text-gray-500 uppercase bg-gray-50 dark:bg-white/5 border-b dark:border-white/10">
                            <tr>
                                <th className="px-6 py-3">Timestamp</th>
                                <th className="px-6 py-3">Student Details</th>
                                <th className="px-6 py-3">Generated By</th>
                                <th className="px-6 py-3">IP Address</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-100 dark:divide-white/5">
                            {loading ? (
                                <tr><td colSpan="4" className="p-6 text-center">Loading logs...</td></tr>
                            ) : filteredLogs.length === 0 ? (
                                <tr><td colSpan="4" className="p-6 text-center">No logs found.</td></tr>
                            ) : (
                                filteredLogs.map(log => (
                                    <tr key={log._id} className="hover:bg-gray-50 dark:hover:bg-white/5">
                                        <td className="px-6 py-4">
                                            <div className="flex items-center gap-2">
                                                <Clock className="h-4 w-4 text-gray-400" />
                                                <span className="font-mono text-xs text-gray-600 dark:text-gray-400">
                                                    {new Date(log.generatedAt).toLocaleString()}
                                                </span>
                                            </div>
                                        </td>
                                        <td className="px-6 py-4">
                                            <p className="font-bold dark:text-white">{log.detailsSnapshot?.name}</p>
                                            <p className="text-xs text-gray-500">{log.detailsSnapshot?.rollNumber} | {log.detailsSnapshot?.course}</p>
                                        </td>
                                        <td className="px-6 py-4">
                                            <span className={`px-2 py-1 rounded text-xs font-bold ${log.generatedBy?.role === 'student' ? 'bg-green-100 text-green-700' : 'bg-purple-100 text-purple-700'}`}>
                                                {log.generatedBy?.name} ({log.generatedBy?.role})
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 font-mono text-xs text-gray-500">
                                            {log.ipAddress || 'N/A'}
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
};

export default IDCardLogs;
